esphomeyaml:
  name: alarm
  platform: ESP8266
  board: esp12e
  
wifi:
  ssid: 'SSID'
  password: 'xxxx'

# Enable logging
logger:

# Enable Home Assistant API
api:
  reboot_timeout: 0s
  
ota:

status_led:
  pin:
    number: GPIO0
    inverted: True

# output:
#   - platform: gpio
#     pin: GPIO3
#     id: wired_siren
#   - platform: gpio
#     pin: GPIO2
#     id: led2_blue
#   - platform: gpio
#     pin: GPIO15
#     id: led2_red

remote_transmitter:
  pin: GPIO4
  carrier_duty_percent: 100%
  
remote_receiver:
  pin: GPIO5
  #dump: rc_switch
  filter : 200us
  
script:
  - id: alarm_detection
    then:
      - if:
          condition:
            switch.is_on: alarm_status
          then:
            - switch.turn_on: wired_siren
            - switch.turn_on: start_siren_ext
          else:
            - switch.turn_on: led2_blue
            - delay: 2s
            - switch.turn_off: led2_blue

binary_sensor:
  - platform: status
    name: "Alarm Status"

  - platform: gpio
    name: "Reset button"
    pin: 
      number: GPIO16
      inverted: True
    filters:
      - delayed_on: 10ms

  - platform: remote_receiver
    name: "PIR Entree"
    device_class: motion
    rc_switch_raw:
      code: '010101010101010101010101'
    filters:
       - delayed_off: 2s
    on_press:
      then:
        - script.execute: alarm_detection
        
  - platform: remote_receiver
    name: "PIR Salon"
    device_class: motion
    rc_switch_raw:
      code: '010101010101010101010101'
    filters:
       - delayed_off: 2s
    on_press:
      then:
        - script.execute: alarm_detection
        
  - platform: remote_receiver
    name: "PIR Test"
    device_class: motion
    rc_switch_raw:
      code: '010101010101010101010101'
    filters:
       - delayed_off: 2s
    on_press:
      then:
        - script.execute: alarm_detection
        
  - platform: remote_receiver
    name: "DOOR Entree"
    device_class: motion
    rc_switch_raw:
      code: '010101010101010101010101'
    filters:
       - delayed_off: 2s
    on_press:
      then:
        - script.execute: alarm_detection
  
switch:
  - platform: remote_transmitter
    name: "Disarm siren ext"
    id : disarm_siren_ext
    icon: "mdi:volume-off"
    repeat : 3
    rc_switch_raw:
      code: '010101010101010101010101'

  - platform: remote_transmitter
    name: "Arm siren ext"
    id : arm_siren_ext
    icon: "mdi:volume-low"
    repeat : 3
    rc_switch_raw:
      code: '010101010101010101010101'

  - platform: remote_transmitter
    name: "Start siren ext"
    id : start_siren_ext
    icon: "mdi:volume-high"
    repeat : 3
    rc_switch_raw:
      code: '010101010101010101010101'
      protocol: 1

  - platform: gpio
    name: "Wired siren"
    icon: "mdi:volume-plus"
    pin: 
      number: GPIO3
      inverted: True
    id: wired_siren

  - platform: gpio
    name: "Led blue"
    icon: "mdi:led-off"
    pin: 
      number: GPIO2
      inverted: True
    id: led2_blue

  - platform: gpio
    name: "Led red"
    icon: "mdi:led-off"
    pin: 
      number: GPIO15
      inverted: True
    id: led2_red

  - platform: template
    name: "Alarm switch"
    id : alarm_status
    icon : "mdi:home-lock"
    optimistic: True
    turn_on_action:
      - switch.turn_on: led2_red
      - switch.turn_on: arm_siren_ext
    turn_off_action:
      - switch.turn_off: led2_red
      - switch.turn_on: disarm_siren_ext
      - switch.turn_off: wired_siren